FROM python

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

RUN chmod +x ./sensor/install.sh

# Setting time zone to Los Angeles
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY . ./

CMD ["python", "main.py"]